apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:AUFbtaCyjIxjqXBEcY0+0K8u+8UIiADA0trwydobZ7TwBn7jS6T0PF2bkDHQhV0Zvr2bVr0Oaqek8dyqyUAlPZG9Thc8rfuKMMoBbscl2pKuuUHXkvpfCFbMjrQ/2+F3/B3BjHTktnrUXuMrcSSwrQOezKj0i/uhIMZ+C3sW4fXYzONENaL4kjI2t+Xr28spoSqUmOLKHcuyxrFjHVInl8Y2KxhanCfOgCpYNFCm55vjaIAVOl0fL2B1TroLpIwLZ1a1kCnajgrqnchTrP1dtNXtf+VE5hUpCK3NQj5ci3Ou1kR4wdlmceDQe9U=,iv:mSupHXQyVEQbu/q8NjdTMHVOpURWdlPH5o+Vk3oXb0U=,tag:S5G3dHtxB7YQ28trRbsH7w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1mdd3zj2gmm4sw6h3l62dv00dp4y8uu628n6fxfax2ftmwqrdtcjq4pmwcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y3dGalo5TTVvYkZIL3pq
            VXBuTmErdEMzb0cwdmNjc3Rnbit1eEdhYURZCmVRZWlOZlMxbXMxUGRsK2VLemZa
            eXpQSXJCb05YR2U1SkMvVEp4RU4zeTgKLS0tIFd4UDNnbUpHdVhkd292WTl5eERp
            NHNKaytlYzJ2dFFSOUtJT2NzM2E5V2MKmy8zVkwZq0kQkaoMIq5bIdXno9beRC8I
            EZdKHuslLH8e1+PFyXh3RJ4rRRu6+DgdLyimtsrv1/0MlWQy3uuD/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-09T19:50:22Z"
    mac: ENC[AES256_GCM,data:MZdQyutBduw8oR3Az5K5feQ6o20xL5s1O0jN+KvSDCkQFUfhDCx2iUSGVrj5vElevcHecXlasa86iAYuzB+tuPsU2brSqrkIHhxwttRy6Lgn6fDgBPwvMMR+j8fol50rcW1HJ+ErLTR9/sK0V0Sv8uakoybxq2XxOCT+v0NQB4I=,iv:7yoTgw3/8IP+c80qXlkD8EJO+6jzEFv4zUGBnJ33Jlk=,tag:lP4r8k1Y7hoXsq1jrdczzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
