apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:VAzyN5u+87g=,iv:q5vymW0ShyHE3eEuxVOON6DiZYXpFPBBLr1IHyie29s=,tag:AomreeQuIOJF5orWo5D1Qg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:c/z8cnzD2ao=,iv:6OZKObtyTa3WfFDWxEoHo+wXylpyinGFFPxfBaOCrxM=,tag:w7u/Ke8xCFTGkvHNVet6xg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - recipient: age1mdd3zj2gmm4sw6h3l62dv00dp4y8uu628n6fxfax2ftmwqrdtcjq4pmwcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbmJUeFN0ZXNRNzlMNjJJ
            SFFRa2l5c3dnalJWQTBMdVZPbzlBN2R3U2hFCnhZVk01c2NFNCtNakV1M0owQlMy
            dkQ0UFpKbU4yb0g0OWRZTWVlenFEZEEKLS0tIHdjakxmN3l2Z0R3UklTK2VnbDgz
            QkxTM3B4UU9UY1QzOXpSL041bXpsbDAKmt4PM9ZO239vsvJiPsri7HwQKW3R+XwF
            yW+/8LG1/JBl+qI/G8Mm/cPX+Zi51zzWJmAK7Ug9uD7Pd50PM2ZpPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-09T15:57:28Z"
    mac: ENC[AES256_GCM,data:3fi0lRC8NNp2P62bWQaKOmUUpZqwTnGfYKmaR5w5aRksRoHfHAI7DFx9LYRm3zEzAO3VrWlRnT7GEK9RiDK25xnL5EsF2krmyzMsSboSUr4LTBH394m1svrXvn7PWjKQZYKXMC7K2F5Np9XRa3GNjGz6VtfTDMSjWmBie7McIuo=,iv:KvHKCN6P8H621W8S82QE3LXURYRsVSGVHdZdRBdZ4D4=,tag:fsWL2d/G79PfnDAigVThfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
